version: "3.9"

services:
  jupyter:
    container_name: lorawan_shbang
    build:
      dockerfile: Dockerfile
    image: lorawan_asap:latest
    ports:
      - "10000:8888"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: jupyter-notebook --NotebookApp.token='' --NotebookApp.password=''
